{{- if .Values.db.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "visit-counter.componentName" (list . "web-db-pvc") }}
spec:
  volumeName: {{ include "visit-counter.componentName" (list . "web-db-pv") }}
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
{{- end }}
