{{- if .Values.db.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "visit-counter.componentName" (list . "web-db") }}
  labels:
    {{- include "visit-counter.labels" . | nindent 4 }}
    {{- include "visit-counter.selectorLabels" (list . "web-db") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "visit-counter.selectorLabels" (list . "web-db") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "visit-counter.labels" . | nindent 8 }}
        {{- include "visit-counter.selectorLabels" (list . "web-db") | nindent 8 }}
    spec:
      {{- if eq .Values.global.stage "prod" }}
      nodeSelector:
        {{- toYaml .Values.web.nodeSelector | nindent 8 }}
      {{- end}}
      containers:
        - name: web-db
          image: postgres:18.3-alpine3.23
          envFrom:
            - secretRef:
                name: {{ include "visit-counter.componentName" (list . "web-db-secret") }}
          ports:
            - containerPort: {{ .Values.db.service.port }}
              name: {{ .Values.db.service.portName }}
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -d "$POSTGRES_DB" -U "$POSTGRES_USER"
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -d "$POSTGRES_DB" -U "$POSTGRES_USER"
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - mountPath: /var/lib/postgresql/18/docker
              name: storage-volume
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: {{ include "visit-counter.componentName" (list . "web-db-pvc") }}
      initContainers:
        - name: busybox
          image: busybox:1.37.0
          command: ["sh", "-c", "rm -rf /var/lib/postgresql/18/docker/lost+found"]
          volumeMounts:
            - mountPath: /var/lib/postgresql/18/docker
              name: storage-volume
{{- end }}
