global:
  stage: prod

web:
  nodeSelector:
    role: web-app
  replicas: 1
  image:
    tag: v4
  service:
    type: NodePort
    nodePort: 32080
db:
  enabled: true  # FIX

aws:
  parameterStoreRegion: us-east-1

autoscaling:
  enabled: false  # FIX

syntheticTraffic:
  enabled: false
