global:
  stage: dev

web:
  replicas: 1
  image:
    repository: orisason1/devops-experts-final-project
    tag: v4
  service:
    type: LoadBalancer
    port: 80
    portName: web-app-http
db:
  enabled: true
  service:
    port: 5432
    portName: web-db-postgres

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCpuUtilizationPercentage: 50

syntheticTraffic:
  enabled: true
