apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "visit-counter.componentName" (list . "web-app") }}
  labels:
    {{- include "visit-counter.labels" . | nindent 4 }}
    {{- include "visit-counter.selectorLabels" (list . "web-app") | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.web.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "visit-counter.selectorLabels" (list . "web-app") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "visit-counter.labels" . | nindent 8 }}
        {{- include "visit-counter.selectorLabels" (list . "web-app") | nindent 8 }}
    spec:
      {{- if eq .Values.global.stage "prod" }}
      nodeSelector:
        {{- toYaml .Values.web.nodeSelector | nindent 8 }}
      {{- end}}
      containers:
        - name: web-app
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ include "visit-counter.componentName" (list . "web-app-configmap") }}
            - secretRef:
                name: {{ include "visit-counter.componentName" (list . "web-db-secret") }}
          ports:
            - containerPort: 5000
              name: {{ .Values.web.service.portName }}
          resources:
            # Low to show HPA fast
            limits:
              cpu: 100m
            requests:
              cpu: 50m
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.web.service.portName }}
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.web.service.portName }}
            initialDelaySeconds: 20
      initContainers:
        - name: wait-for-db
          image: busybox:1.37.0
          envFrom:
            - secretRef:
                name: {{ include "visit-counter.componentName" (list . "web-db-secret") }}
          command:
          - sh
          - -c
          - |
            echo "Waiting for database service..."

            {{- if .Values.db.enabled }}
            DB_HOST="{{ include "visit-counter.componentName" (list . "web-db-svc") }}"
            DB_PORT="{{ .Values.db.service.port }}"
            {{- else if eq .Values.global.stage "prod" }}
            DB_HOST="${DB_HOST}"
            DB_PORT=5432
            {{- end }}

            until nc -z "${DB_HOST}" "${DB_PORT}"; do
              echo "DB not ready, sleeping 2s..."
              sleep 2
            done
            echo "DB is up!"
