apiVersion: v1
kind: Service
metadata:
  name: {{ include "visit-counter.componentName" (list . "web-app-svc") }}
  labels:
    {{- include "visit-counter.labels" . | nindent 4 }}
    {{- include "visit-counter.selectorLabels" (list . "web-app") | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "visit-counter.selectorLabels" (list . "web-app") | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.portName }}
