{{- if and (not .Values.db.enabled) (eq .Values.global.stage "prod") }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.aws.parameterStoreRegion }}
{{- end }}
