{{- if and (not .Values.db.enabled) (eq .Values.global.stage "prod") }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "visit-counter.componentName" (list . "web-db-secret") }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: {{ include "visit-counter.componentName" (list . "web-db-secret") }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: /devops-experts-final-project/prod/db-credentials
{{- end }}
