apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "visit-counter.componentName" (list . "web-db-pv") }}   # DONE2
spec:
  volumeMode: Filesystem
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/web-app-db-postgres/
    type: DirectoryOrCreate
