apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "visit-counter.componentName" (list . "web-db-pvc") }}   # DONE2
spec:
  volumeName: {{ include "visit-counter.componentName" (list . "web-db-pv") }}   # DONE2
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
