apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.webAppDbPvc.name }}   # DONE
spec:
  volumeName: {{ .Values.webAppDbPv.name }}   # DONE
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
