apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "visit-counter.componentName" (list . "web-app-db") }}   # DONE2
  labels:
    app: {{ .Values.webDeployment.name }}-db   # DONE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.webDeployment.name }}-db   # DONE
  template:
    metadata:
      labels:
        app: {{ .Values.webDeployment.name }}-db   # DONE
    spec:
      containers:
        - name: web-app-db
          image: postgres:18.3-alpine3.23
          envFrom:
            - secretRef:
                name: {{ include "visit-counter.componentName" (list . "web-app-db-secret") }}   # DONE2
          ports:
            - containerPort: {{ .Values.dbService.port }}   # DONE
              name: {{ .Values.dbService.portName }}   # DONE
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -d "$POSTGRES_DB" -U "$POSTGRES_USER"
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -d "$POSTGRES_DB" -U "$POSTGRES_USER"
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - mountPath: /var/lib/postgresql/18/docker
              name: storage-volume
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: {{ include "visit-counter.componentName" (list . "web-app-db-pvc") }}   # DONE2
      initContainers:
        - name: busybox
          image: busybox:latest
          command: ["sh", "-c", "rm -rf /var/lib/postgresql/18/docker/lost+found"]
          volumeMounts:
            - mountPath: /var/lib/postgresql/18/docker
              name: storage-volume
