apiVersion: v1
kind: Service
metadata:
  name: {{ include "visit-counter.componentName" (list . "web-db-svc") }}   # DONE2
  labels:
    {{- include "visit-counter.labels" . | nindent 4 }}
    {{- include "visit-counter.selectorLabels" (list . "web-db-svc") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "visit-counter.selectorLabels" (list . "web-db") | nindent 4 }}   # DONE
  ports:
    - protocol: TCP
      port: {{ .Values.dbService.port }}   # FIX
      targetPort: {{ .Values.dbService.portName }}   # FIX
