apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webService.name }}   # DONE
  labels:
    app: {{ .Values.webDeployment.name }}   # DONE
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.webDeployment.name }}   # DONE
  ports:
    - protocol: TCP
      port: {{ .Values.webService.port }}   # DONE
      targetPort: {{ .Values.webService.portName }}   # DONE
