apiVersion: v1
kind: Service
metadata:
  name: {{ include "visit-counter.componentName" (list . "web-svc") }}   # DONE2
  labels:
    app: {{ .Values.webDeployment.name }}   # DONE
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.webDeployment.name }}   # DONE
  ports:
    - protocol: TCP
      port: {{ .Values.webService.port }}   # DONE
      targetPort: {{ .Values.webService.portName }}   # DONE
