apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "visit-counter.componentName" (list . "web-app") }}  # DONE2
  labels:
    {{- include "visit-counter.labels" . | nindent 4 }}
    {{- include "visit-counter.selectorLabels" (list . "web-app") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "visit-counter.selectorLabels" (list . "web-app") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "visit-counter.labels" . | nindent 8 }}
        {{- include "visit-counter.selectorLabels" (list . "web-app") | nindent 8 }}
    spec:
      containers:
        - name: web-app
          image: orisason1/devops-experts-final-project:v4
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ include "visit-counter.componentName" (list . "web-app-configmap") }}   # DONE2
            - secretRef:
                name: {{ include "visit-counter.componentName" (list . "web-db-secret") }}   # DONE2
          ports:
            - containerPort: 5000
              name: {{ .Values.web.service.portName }}   # DONE3
          resources:
            # Low to show HPA fast
            limits:
              cpu: 100m
            requests:
              cpu: 50m
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.web.service.portName }}   # DONE3
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.web.service.portName }}    # DONE3
            initialDelaySeconds: 20
      initContainers:
      - name: wait-for-db
        image: busybox:1.37.0
        command:
        - sh
        - -c
        - |
          echo "Waiting for database service..."
          # DONE-svc name + port
          until nc -z {{ include "visit-counter.componentName" (list . "web-db-svc") }} {{ .Values.db.service.port }}; do   # DONE3
            echo "DB not ready, sleeping 2s..."
            sleep 2
          done
          echo "DB is up!"
