apiVersion: v1
kind: Service
metadata:
  name: {{ include "visit-counter.componentName" (list . "web-app-svc") }}   # DONE2
  labels:
    {{- include "visit-counter.labels" . | nindent 4 }}
    {{- include "visit-counter.selectorLabels" (list . "web-app") | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "visit-counter.selectorLabels" (list . "web-app") | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.webService.port }}   # FIX
      targetPort: {{ .Values.webService.portName }}   # FIX
