# Prometheus stamps `cluster="doesn't-matter"` onto data ONLY when it leaves the cluster (outbound alerts/remote write).
# Included here because dashboard 15757 panels requires $cluster variable.
# If we don't do that, $cluster will be empty and some panels will show an error.
prometheus:
  server:
    global:
      external_labels:
        cluster: "doesn't-matter"

grafana:
  sidecar:
    # Instead of letting Grafana scan every single ConfigMap in the Kubernetes cluster,
    # we tell the sidecar to only intercept ConfigMaps labeled with "grafana_datasource: '1'".
    datasources:
      enabled: true
      label: grafana_datasource
      labelValue: "1"
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL

  # Creating new datasource in Grafana, so it will use data of Prometheus
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://monitoring-prometheus-server.monitoring.svc.cluster.local
          access: proxy
          isDefault: true # Immediately query this data source without needing manual adjustments in the UI
