apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-app-db-pvc
spec: 
  volumeName: web-app-db-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
