apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-app-db
  labels:
    app: web-app-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-db
  template:
    metadata:
      labels:
        app: web-app-db
    spec:
      containers:
        - name: web-app-db
          image: postgres:18.3-alpine3.23
          envFrom:
            - secretRef:
                name: web-app-db-secret
          ports:
            - containerPort: 5432
              name: db-svc
          volumeMounts:
            - mountPath: /var/lib/postgresql/18/docker
              name: storage-volume
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: web-app-db-pvc
      initContainers:
        - name: busybox
          image: busybox:latest
          command: ["sh", "-c", "rm -rf /var/lib/postgresql/18/docker/lost+found"]
          volumeMounts:
            - mountPath: /var/lib/postgresql/18/docker
              name: storage-volume

