apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: orisason1/devops-experts-s4e3:v3
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: web-app-configmap
            - secretRef:
                name: web-app-db-secret
          ports:
            - containerPort: 5000
              name: http-web-svc
          resources:
            # Low to show HPA fast
            limits:
              cpu: 100m
            requests:
              cpu: 50m
          readinessProbe:
            httpGet:
              path: /health
              port: http-web-svc
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http-web-svc
            initialDelaySeconds: 20
      initContainers:
      - name: wait-for-db
        image: busybox:1.37.0
        command:
        - sh
        - -c
        - |
          echo "Waiting for database service..."
          until nc -z db-svc 5432; do
            echo "DB not ready, sleeping 2s..."
            sleep 2
          done
          echo "DB is up!"
