services:
  db:
    image: postgres:18.3-alpine3.23
    container_name: db
    env_file: 
      - './env/postgres.env'
    volumes:
      - postgres-vol:/var/lib/postgresql
    healthcheck:
      # requires because by default, depends_on only waits for the database container to start,
      # not for the database service inside it to be ready to accept connections
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 3
  web:
    depends_on:
      db:
        condition: service_healthy
    build: .
    container_name: web-app
    ports:
      - 80:5000
    env_file:
      - './env/postgres.env'
      - './env/web-app.env'

volumes:
  postgres-vol: {}